# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import object_tracking_pb2 as object__tracking__pb2


class ObjectTrackingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.track_objects = channel.unary_unary(
                '/protos.ObjectTracking/track_objects',
                request_serializer=object__tracking__pb2.Request.SerializeToString,
                response_deserializer=object__tracking__pb2.TrackingResponse.FromString,
                )


class ObjectTrackingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def track_objects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectTrackingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'track_objects': grpc.unary_unary_rpc_method_handler(
                    servicer.track_objects,
                    request_deserializer=object__tracking__pb2.Request.FromString,
                    response_serializer=object__tracking__pb2.TrackingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.ObjectTracking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectTracking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def track_objects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.ObjectTracking/track_objects',
            object__tracking__pb2.Request.SerializeToString,
            object__tracking__pb2.TrackingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
